// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU2mtTGX-YDHMaEl0XwNgcWeLm1q3CZU4',
    appId: '1:125056695111:web:8e0f71795682993ebd6a62',
    messagingSenderId: '125056695111',
    projectId: 'sem6-mini-project',
    authDomain: 'sem6-mini-project.firebaseapp.com',
    storageBucket: 'sem6-mini-project.appspot.com',
    measurementId: 'G-P0X2XPJFRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkJDJ60TUjNuCG_IvNmnnfShkVPYxjsU0',
    appId: '1:125056695111:android:cbf53e0b42b9f3d6bd6a62',
    messagingSenderId: '125056695111',
    projectId: 'sem6-mini-project',
    storageBucket: 'sem6-mini-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhTsJjob5iTZDSbdznmiO9XaD7NQnTcLQ',
    appId: '1:125056695111:ios:dfb586a87187870fbd6a62',
    messagingSenderId: '125056695111',
    projectId: 'sem6-mini-project',
    storageBucket: 'sem6-mini-project.appspot.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhTsJjob5iTZDSbdznmiO9XaD7NQnTcLQ',
    appId: '1:125056695111:ios:dfb586a87187870fbd6a62',
    messagingSenderId: '125056695111',
    projectId: 'sem6-mini-project',
    storageBucket: 'sem6-mini-project.appspot.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU2mtTGX-YDHMaEl0XwNgcWeLm1q3CZU4',
    appId: '1:125056695111:web:03e4e002d1ec847fbd6a62',
    messagingSenderId: '125056695111',
    projectId: 'sem6-mini-project',
    authDomain: 'sem6-mini-project.firebaseapp.com',
    storageBucket: 'sem6-mini-project.appspot.com',
    measurementId: 'G-CZ5X700K45',
  );

}